### PR TITLE
Move Common Criteria content to a dedicated collection

### PR DESCRIPTION
**Pull request by rpelisse**
@hcherukuri double-check that I did not forget anything! I suggest we keep only 'main' for now. We'll set up the upstream branch when we need to perform an upstream release.

### CODE REVIEW

**Comment by hcherukuri** [comment]
galaxy.yml has " community.general: '>=3.4.0'" and playbook.yml still has  "common_criteria" role added. Could you please remove them.

**Comment by rpelisse** [comment]
@hcherukuri I fixed the galaxy.yml, thanks for spotting that! However, I don't find any import of the [common_criteria role](https://github.com/ansible-middleware/jws-ansible-playbook/pull/26/files#diff-6377f8a1937054624eac73b02854e7f99081cb731582fcecd1b435c5ded73120R38) in the playbook.yml. Did you meant another file?

**Comment by hcherukuri** [comment]
> @hcherukuri I fixed the galaxy.yml, thanks for spotting that! However, I don't find any import of the [common_criteria role](https://github.com/ansible-middleware/jws-ansible-playbook/pull/26/files#diff-6377f8a1937054624eac73b02854e7f99081cb731582fcecd1b435c5ded73120R38) in the playbook.yml. Did you meant another file?

https://github.com/ansible-middleware/jws-ansible-playbook/blob/main/playbook.yml#L39

**Comment by hcherukuri** [comment]
LGTM

**Pull request merged**
